from UQpy.sample_methods.stratifications.DelaunayStratification import DelaunaySTS
from UQpy.sample_methods.stratifications.RectangularStratification import RectangularSTS
from UQpy.sample_methods.stratifications.VoronoiStratification import VoronoiSTS
