from UQpy.surrogates.polynomial_chaos.regressions.Lasso import LassoRegression
from UQpy.surrogates.polynomial_chaos.regressions.LeastSquares import LeastSquareRegression
from UQpy.surrogates.polynomial_chaos.regressions.Ridge import RidgeRegression
